#!/usr/bin/env bash
# check arguments :

if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
        exit 1
fi
# assign parameters to variables:

path_to_file=$1
ip=$2
username=$3
path_to_ssh_key=$4
# disable strict host key checking

scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
#if transfered successfully:
if [ $? -eq 0 ]
then
	echo "file successfully transfered "
else
	echo "failed to transfere file"
fi

	
