#!/usr/bin/env bash
# install nginx web server
sudo apt-get -y update
sudo apt-get -y install nginx 
sudo ufw "Nginx HTTP"
echo "Hwllo World!" | sudo tee /var/www/html/index.html
sudo nginx -t
sudo service nginx reload
